; 1) Настроил mypy для Django, указав путь к settings.py. Это нужно было чтоб убрать ошибки проверки mypy
; из-за того, что он не распознавал phonenumber_field, так как у phonenumber_field нет type stubs;
; 2) Пробовал игнорировать phonenumber_field в mypy.ini, но это не сработало и поэтому пришлось добавить
; в код (users/models.py) вот это "# type: ignore" на импорт PhoneNumberField, и ошибка исчезла.


[mypy]
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = config.settings

[mypy.phonenumber_field.*]
ignore_missing_imports = True